name: Deploy Cdk Environment
run-name: Deploy branch ${{ github.ref_name }} by @${{ github.actor }}
on:  
  workflow_dispatch:

jobs:
  deploy-s3:
    name: Upload assets to S3
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        id: env
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "test" ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=dev2" >> $GITHUB_OUTPUT
          fi
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 587
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: nguyentantai13031999@gmail.com
          # Optional (recommended) mail server password:
          password: rhiuoputwpzvcgrc
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: nguyentantai13031999@gmail.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://index.html
          # Optional carbon copy recipients:
          cc: nguyentantai13031999@gmail.com
          # Optional blind carbon copy recipients:
          bcc: nguyentantai13031999@gmail.com
          # Optional recipient of the email response:
          reply_to: nguyentantai13031999@gmail.com
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
          # Optional nodemailerlog: true/false
          nodemailerlog: false
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          nodemailerdebug: false
          # Optional custom SMTP MAIL FROM address (overrides username):
          envelope_from: nguyentantai13031999@gmail.com
          # Optional custom SMTP RCPT TO addresses (overrides to, cc, bcc):
          envelope_to: nguyentantai13031999@gmail.com,nguyentantai13031999@gmail.com
  
