name: Deploy Cdk Environment
#run-name: Deploy branch ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - master
      - test
      - dev
      - RIKKEI-857
      
  workflow_dispatch:
