name: Deploy Cdk Environment
run-name: Deploy branch ${{ github.ref_name }} by @${{ github.actor }}
on:  
  workflow_dispatch:

jobs:
  deploy-s3:
    name: Upload assets to S3
    runs-on: ubuntu-latest
    steps: