name: Deploy Cdk Environment
run-name: Deploy branch ${{ github.ref_name }} by @${{ github.actor }}
on:  
  workflow_dispatch:

jobs:
  deploy-s3:
    name: Upload assets to S3
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        id: env
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "test" ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=dev2" >> $GITHUB_OUTPUT
          fi
  send-mail:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install

      - name: Send Email
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          MAIL_HOST: ${{ secrets.SERVER_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          SERVICE: ${{ secrets.SERVICE }}
        run: |
          node .github/scripts/send-email.mjs
          if [ $? -ne 0 ]; then
            echo "Error: Failed to send email"
            exit 1
          fi
  
